-- World Happiness Report MySQL analysis
-- MySQL version: 8.0+
-- Purpose: SQL learning version for the World Happiness portfolio project

DROP DATABASE IF EXISTS world_happiness_learning;
CREATE DATABASE world_happiness_learning DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE world_happiness_learning;

DROP TABLE IF EXISTS world_happiness;

CREATE TABLE world_happiness (
    id INT AUTO_INCREMENT PRIMARY KEY,
    `year` SMALLINT NOT NULL,
    country VARCHAR(120) NOT NULL,
    region VARCHAR(120) NULL,
    rank_no INT NOT NULL,
    score DECIMAL(6, 3) NOT NULL,
    gdp DECIMAL(8, 5) NULL,
    social_support DECIMAL(8, 5) NULL,
    life_expectancy DECIMAL(8, 5) NULL,
    freedom DECIMAL(8, 5) NULL,
    generosity DECIMAL(8, 5) NULL,
    corruption DECIMAL(8, 5) NULL,
    KEY idx_year_score (`year`, score),
    KEY idx_country_year (country, `year`),
    KEY idx_region_year (region, `year`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4;

-- Import cleaned CSV generated by Python.
-- If LOCAL INFILE is disabled, use MySQL Workbench import wizard with the same CSV.
-- On some machines you need: SET GLOBAL local_infile = 1;
-- If relative paths do not work in your client, replace this path with your local absolute path.
LOAD DATA LOCAL INFILE 'projects/world-happiness-report/outputs/tables/world_happiness_clean_2015_2019.csv'
INTO TABLE world_happiness
CHARACTER SET utf8mb4
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 LINES
(@year, @country, @region, @rank_no, @score, @gdp, @social_support, @life_expectancy, @freedom, @generosity, @corruption)
SET
    `year` = CAST(NULLIF(TRIM(BOTH '\r' FROM @year), '') AS UNSIGNED),
    country = NULLIF(TRIM(BOTH '\r' FROM @country), ''),
    region = NULLIF(TRIM(BOTH '\r' FROM @region), ''),
    rank_no = CAST(NULLIF(TRIM(BOTH '\r' FROM @rank_no), '') AS UNSIGNED),
    score = CAST(NULLIF(TRIM(BOTH '\r' FROM @score), '') AS DECIMAL(6, 3)),
    gdp = CAST(NULLIF(TRIM(BOTH '\r' FROM @gdp), '') AS DECIMAL(8, 5)),
    social_support = CAST(NULLIF(TRIM(BOTH '\r' FROM @social_support), '') AS DECIMAL(8, 5)),
    life_expectancy = CAST(NULLIF(TRIM(BOTH '\r' FROM @life_expectancy), '') AS DECIMAL(8, 5)),
    freedom = CAST(NULLIF(TRIM(BOTH '\r' FROM @freedom), '') AS DECIMAL(8, 5)),
    generosity = CAST(NULLIF(TRIM(BOTH '\r' FROM @generosity), '') AS DECIMAL(8, 5)),
    corruption = CAST(NULLIF(TRIM(BOTH '\r' FROM @corruption), '') AS DECIMAL(8, 5));

-- 1. Data quality overview
-- Business question: is this dataset reliable enough for analysis?
SELECT
    COUNT(*) AS total_rows,
    COUNT(DISTINCT country) AS distinct_countries,
    MIN(`year`) AS min_year,
    MAX(`year`) AS max_year,
    SUM(CASE WHEN region IS NULL THEN 1 ELSE 0 END) AS missing_region_rows,
    SUM(CASE WHEN corruption IS NULL THEN 1 ELSE 0 END) AS missing_corruption_rows
FROM world_happiness;

-- Expected:
-- total_rows = 782
-- missing_region_rows = 8
-- missing_corruption_rows = 1

-- 2. Duplicate check by country and year
-- Business question: is each country unique within each year?
SELECT
    COALESCE(SUM(CASE WHEN cnt > 1 THEN 1 ELSE 0 END), 0) AS duplicate_country_year_groups,
    COALESCE(SUM(CASE WHEN cnt > 1 THEN cnt - 1 ELSE 0 END), 0) AS duplicate_extra_rows
FROM (
    SELECT
        `year`,
        country,
        COUNT(*) AS cnt
    FROM world_happiness
    GROUP BY `year`, country
) AS t;

-- 3. Missing detail
-- Business question: which rows still need data-quality explanation?
SELECT
    `year`,
    country,
    region,
    corruption
FROM world_happiness
WHERE region IS NULL
   OR corruption IS NULL
ORDER BY country, `year`;

-- 4. Annual trend
-- Business question: did the global average happiness score move clearly from 2015 to 2019?
SELECT
    `year`,
    COUNT(DISTINCT country) AS countries,
    ROUND(AVG(score), 3) AS avg_score,
    ROUND(AVG(gdp), 3) AS avg_gdp,
    ROUND(AVG(social_support), 3) AS avg_social_support,
    ROUND(AVG(life_expectancy), 3) AS avg_life_expectancy
FROM world_happiness
GROUP BY `year`
ORDER BY `year`;

-- 5. 2019 Top 10 and Bottom 10 countries
-- Business question: which markets have the strongest and weakest overall social environment in 2019?
WITH ranked_2019 AS (
    SELECT
        country,
        region,
        rank_no,
        score,
        gdp,
        social_support,
        life_expectancy,
        ROW_NUMBER() OVER (ORDER BY score DESC) AS high_rank,
        ROW_NUMBER() OVER (ORDER BY score ASC) AS low_rank
    FROM world_happiness
    WHERE `year` = 2019
)
SELECT
    1 AS sort_group,
    'top10' AS group_type,
    high_rank AS display_rank,
    country,
    region,
    score,
    gdp,
    social_support,
    life_expectancy
FROM ranked_2019
WHERE high_rank <= 10
UNION ALL
SELECT
    2 AS sort_group,
    'bottom10' AS group_type,
    low_rank AS display_rank,
    country,
    region,
    score,
    gdp,
    social_support,
    life_expectancy
FROM ranked_2019
WHERE low_rank <= 10
ORDER BY sort_group, display_rank;

-- Expected:
-- top1 = Finland
-- bottom1 = South Sudan

-- 6. Score change from 2015 to 2019
-- Business question: which countries improved or deteriorated the most?
WITH yearly_score AS (
    SELECT
        country,
        MAX(CASE WHEN `year` = 2015 THEN score END) AS score_2015,
        MAX(CASE WHEN `year` = 2019 THEN score END) AS score_2019
    FROM world_happiness
    WHERE `year` IN (2015, 2019)
    GROUP BY country
    HAVING score_2015 IS NOT NULL
       AND score_2019 IS NOT NULL
),
delta AS (
    SELECT
        country,
        score_2015,
        score_2019,
        ROUND(score_2019 - score_2015, 3) AS delta_2019_vs_2015
    FROM yearly_score
),
ranked_delta AS (
    SELECT
        country,
        score_2015,
        score_2019,
        delta_2019_vs_2015,
        ROW_NUMBER() OVER (ORDER BY delta_2019_vs_2015 DESC) AS increase_rank,
        ROW_NUMBER() OVER (ORDER BY delta_2019_vs_2015 ASC) AS decrease_rank
    FROM delta
)
SELECT
    1 AS sort_group,
    'increase_top10' AS group_type,
    increase_rank AS display_rank,
    country,
    score_2015,
    score_2019,
    delta_2019_vs_2015
FROM ranked_delta
WHERE increase_rank <= 10
UNION ALL
SELECT
    2 AS sort_group,
    'decrease_top10' AS group_type,
    decrease_rank AS display_rank,
    country,
    score_2015,
    score_2019,
    delta_2019_vs_2015
FROM ranked_delta
WHERE decrease_rank <= 10
ORDER BY sort_group, display_rank;

-- Expected:
-- largest increase = Benin
-- largest decrease = Venezuela

-- 7. Region performance in 2019
-- Business question: which regions perform better on average, and how large is the sample?
SELECT
    region,
    COUNT(DISTINCT country) AS countries,
    ROUND(AVG(score), 3) AS avg_score,
    ROUND(AVG(gdp), 3) AS avg_gdp,
    ROUND(AVG(social_support), 3) AS avg_social_support,
    ROUND(AVG(life_expectancy), 3) AS avg_life_expectancy,
    ROUND(MIN(score), 3) AS min_score,
    ROUND(MAX(score), 3) AS max_score
FROM world_happiness
WHERE `year` = 2019
  AND region IS NOT NULL
GROUP BY region
ORDER BY avg_score DESC;

-- 8. Region trend from 2015 to 2019
-- Business question: which regions improved or declined on average?
WITH region_year AS (
    SELECT
        region,
        `year`,
        AVG(score) AS avg_score,
        COUNT(DISTINCT country) AS countries
    FROM world_happiness
    WHERE region IS NOT NULL
    GROUP BY region, `year`
),
region_pivot AS (
    SELECT
        region,
        MAX(CASE WHEN `year` = 2015 THEN avg_score END) AS avg_score_2015,
        MAX(CASE WHEN `year` = 2019 THEN avg_score END) AS avg_score_2019,
        MAX(CASE WHEN `year` = 2019 THEN countries END) AS countries_2019
    FROM region_year
    GROUP BY region
)
SELECT
    region,
    countries_2019,
    ROUND(avg_score_2015, 3) AS avg_score_2015,
    ROUND(avg_score_2019, 3) AS avg_score_2019,
    ROUND(avg_score_2019 - avg_score_2015, 3) AS delta_2019_vs_2015
FROM region_pivot
WHERE avg_score_2015 IS NOT NULL
  AND avg_score_2019 IS NOT NULL
ORDER BY delta_2019_vs_2015 DESC;

-- 9. 2019 indicator correlation with happiness score
-- Business question: which indicators move most closely with happiness score?
WITH indicator_long AS (
    SELECT `year`, country, score, 'gdp' AS metric, gdp AS indicator_value FROM world_happiness
    UNION ALL
    SELECT `year`, country, score, 'social_support' AS metric, social_support AS indicator_value FROM world_happiness
    UNION ALL
    SELECT `year`, country, score, 'life_expectancy' AS metric, life_expectancy AS indicator_value FROM world_happiness
    UNION ALL
    SELECT `year`, country, score, 'freedom' AS metric, freedom AS indicator_value FROM world_happiness
    UNION ALL
    SELECT `year`, country, score, 'generosity' AS metric, generosity AS indicator_value FROM world_happiness
    UNION ALL
    SELECT `year`, country, score, 'corruption' AS metric, corruption AS indicator_value FROM world_happiness
)
SELECT
    metric,
    COUNT(*) AS sample_size,
    ROUND(
        (AVG(score * indicator_value) - AVG(score) * AVG(indicator_value))
        / NULLIF(STDDEV_POP(score) * STDDEV_POP(indicator_value), 0),
        3
    ) AS corr_with_score
FROM indicator_long
WHERE `year` = 2019
  AND indicator_value IS NOT NULL
GROUP BY metric
ORDER BY corr_with_score DESC;

-- 10. Score segmentation in 2019
-- Business question: how do high-score, middle-score, and low-score countries differ?
SELECT
    CASE
        WHEN score >= 6.5 THEN 'high_score_6_5_plus'
        WHEN score >= 4.5 THEN 'middle_score_4_5_to_6_5'
        ELSE 'low_score_below_4_5'
    END AS score_segment,
    COUNT(*) AS countries,
    ROUND(AVG(score), 3) AS avg_score,
    ROUND(AVG(gdp), 3) AS avg_gdp,
    ROUND(AVG(social_support), 3) AS avg_social_support,
    ROUND(AVG(life_expectancy), 3) AS avg_life_expectancy,
    ROUND(AVG(freedom), 3) AS avg_freedom,
    ROUND(AVG(corruption), 3) AS avg_corruption
FROM world_happiness
WHERE `year` = 2019
GROUP BY score_segment
ORDER BY avg_score DESC;

-- 11. Diagnostic view: higher GDP quartile but lower happiness quartile
-- Business question: which countries may need deeper qualitative diagnosis?
WITH quartile_2019 AS (
    SELECT
        country,
        region,
        score,
        gdp,
        social_support,
        life_expectancy,
        freedom,
        NTILE(4) OVER (ORDER BY gdp) AS gdp_quartile,
        NTILE(4) OVER (ORDER BY score) AS score_quartile
    FROM world_happiness
    WHERE `year` = 2019
      AND gdp IS NOT NULL
)
SELECT
    country,
    region,
    score,
    gdp,
    social_support,
    life_expectancy,
    freedom,
    gdp_quartile,
    score_quartile
FROM quartile_2019
WHERE gdp_quartile >= 3
  AND score_quartile <= 2
ORDER BY gdp_quartile DESC, score_quartile ASC, score ASC;

-- 12. Country profile lookup
-- Business question: when a stakeholder asks about one country, how do we quickly show its trend?
SELECT
    `year`,
    country,
    region,
    rank_no,
    score,
    gdp,
    social_support,
    life_expectancy,
    freedom,
    generosity,
    corruption
FROM world_happiness
WHERE country IN ('Finland', 'South Sudan', 'Benin', 'Venezuela')
ORDER BY country, `year`;
